### ISSUE TITLE
[Bug report]: z-index issue when mobile side menu opened

### ISSUE THREAD

**Issue by furkick** [scania-digital-design-system/sdds#360]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported.
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md).
- [X] I have checked the lastest version if the bug exist there. See all avaliable packages at [npmJS.com](https://www.npmjs.com/search?q=%40scania)
- [X] I have made sure that the issue comes from SDDS packages by removing SDDS from my project as a test.
- [X] I have followed the installation guide.

### Package

@scania/components

### Package versions

@scania/components: 4.0.0

### Browser

Chrome

### Framework

Angular

### Version

Angular 13.3.0

### Reproduction steps

1. Trigger mobile view
2. Open side menu
3. Observe the menu and other components

### Code example

When `sdds-nav__mob-menu--opened` is used on `sdds-nav` the z-index does not take priority over the correct components. See screenshot.

### Screenshots

![MicrosoftTeams-image](https://user-images.githubusercontent.com/7430414/164632536-b8e264ac-79de-48fc-878c-865015449ff4.png)

### Expected behaviour

The mobile side menu should be in the foreground. 

### Contact information

christopher.halfpenny@scania.com

[AB#1887](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1887)

**Comment by furkick** [comment]
The Avatar menu also suffers the same issue.

`sdds-nav__avatar-menu`

**Comment by alexlioliopoulos** [comment]
Thanks for reporting! We will soon start working on a fix for this.

**Comment by alexlioliopoulos** [comment]
Should be fixed now!

**Comment by alexlioliopoulos** [comment]
@furkick Was this actually fixed? Can you confirm?

**Comment by furkick** [comment]
They still have the issue, unfortunately.

![image](https://user-images.githubusercontent.com/7430414/189657513-4ab86ea7-9bbe-4a09-9065-59eb5156d038.png)

![image](https://user-images.githubusercontent.com/7430414/189657578-9a6ab44d-c78e-473d-ab8b-4bd7d91d077b.png)

**Comment by alexlioliopoulos** [comment]
And you have our newest packages, right? There was some mixup and we weren't sure if we closed this because it was worked on by an employee that left the company or not.

**Comment by furkick** [comment]
These are the versions in use from the screenshot provided.

![image](https://user-images.githubusercontent.com/7430414/190640711-e2d4d759-e289-44ed-b944-11c47c6678a2.png)

**Comment by furkick** [comment]
Has the z-index for the site been discussed? as we are still having to use our own CSS to resolve these issues.

**Comment by mJarsater** [comment]
I am closing this issue due to inactivity. If the issue still persists, feel free to reach out to our PO Johan Nilo.
